### ISSUE TITLE
Feature: sort asc/desc on column header click

### ISSUE THREAD

**Issue by Scrounger** [Cleveroad/AdaptiveTableLayout#1]
Really an amzing library, thanks for creating it!
Could you please implement a sort function for column header click event?

**Comment by yarovoiag** [comment]
Thanks, in near future this feature will be implemented.

**Comment by yarovoiag** [comment]
Sorting by asc/desc could be implemented by your side. Main goal this library is showing big data in table. To implement this feature you should remember that library could works with big data (100k+ lines) and if you want to sort by column, you should sort all 100k+ lines. It could take too much time to user.
