### ISSUE TITLE
Column resizing

### ISSUE THREAD

**Issue by rdonuk** [Cleveroad/AdaptiveTableLayout#10]
Is it possible to resize columns (auto and manuel) according to their contents?

**Comment by yarovoiag** [comment]
To draw cells layout needs to know their width and heights. 
1) Auto resize. If we want to calculate width for columns according their content we should remember that text could be very long. In this case one column could have width all screen or 100k+ pixels. So we need to have width and height for each column and row.
2) Manual resize. If we talking about change width or height of cell by "drag and drop", this feature couldn't be implemented in near future.
You could fork lib and implemented this feature.
