### ISSUE TITLE
Spammy advertising

### ISSUE THREAD

**Issue by dylanpyle** [Cleveroad/AdaptiveTableLayout#14]
I just received a spam email from info@cleveroad.com advertising this repository. It seems I've been added to some sort of mailing list also, since there's an unsubscribe link. I have expressed no interest in this and have not agreed to receive any notifications.

---

![screen shot 2017-07-11 at 11 58 46 am](https://user-images.githubusercontent.com/806257/28085392-7c4a7a26-6630-11e7-9b01-0cde07a0403c.png)

---

This violates [the GitHub terms of service](https://help.github.com/articles/github-terms-of-service/#3-conduct-restrictions), which states:

> While using GitHub, you agree that you will not under any circumstances... use our servers for any form of excessive automated bulk activity (for example, spamming), or relay any other form of unsolicited advertising or solicitation through our servers

> You may not scrape GitHub for spamming purposes

> If you collect any GitHub User's Personal Information from GitHub, you agree that you will only use the Personal Information you gather for the purpose for which our User has authorized it

**Comment by jekaUA** [comment]
We are really sorry that our email seems spammy to you as it was sent with good intentions. Considering you as an active and keen GitHub user, we thought you might be interested in another library that gains popularity day by day. We’re sorry to have bothered you and that will not happen again.
