### ISSUE TITLE
Feature: only view mode

### ISSUE THREAD

**Issue by Scrounger** [Cleveroad/AdaptiveTableLayout#2]
Could you please implement an only view mode, so thats not possible to edit the cells?
I would like to use your library only for viewing a table.

**Comment by sunnykinger** [comment]
+1

**Comment by yarovoiag** [comment]
I'll include this feature to next release.

**Comment by yarovoiag** [comment]
Implemented "Drag and Drop" enabled or disabled mode in version 1.1.1
