### ISSUE TITLE
How to use the pagination in the view?

### ISSUE THREAD

**Issue by eugenio-caicedo** [Cleveroad/AdaptiveTableLayout#22]
I am using this library for the pagination:

https://github.com/tosslife/PullLoadView

But I can not integrate it with the AdaptiveTableLayout

**Comment by yarovoiag** [comment]
Hi @eugenio-caicedo, there isn't RecyclerView in the library, so you cannot use pagination. There is cache in CsvFileDataSourceImpl.java.
