### ISSUE TITLE
Behavior with AppBarLayout

### ISSUE THREAD

**Issue by formatBCE** [Cleveroad/AdaptiveTableLayout#23]
Trying to use this lib together with AppBarLayout, to scroll Toolbar up before scrolling view itself. For this, i wrapped table containing layout to NestedScrollView, but can't achieve proper work - looks like TableLayout does not support such behavior. Could you please take a look?

**Comment by tifezh** [comment]
@formatBCE Did you solve it?

**Comment by formatBCE** [comment]
@tifezh yes, i managed to make it working by forking and digging into code.
You may see my fork https://github.com/formatBCE/AdaptiveTableLayout, 
but be aware, that a lot was changed there to support dynamic data sets as well.

**Comment by tnam0x** [comment]
Could you tell me what part of code you changed to fix this issue?

**Comment by formatBCE** [comment]
@namtran4194 sorry for late response - had busy days.
Changes were made in AdaptiveTableLayout class:

1. `@Override
    public boolean onDown(MotionEvent e) {
        // stop smooth scrolling
        if (!mScrollerRunnable.isFinished()) {
            mScrollerRunnable.forceFinished();
        }
        startNestedScroll(ViewCompat.SCROLL_AXIS_VERTICAL);
        return true;
    }`
here "startNestedScroll" was added.

2. "scrollBy" method fixed - without that fix nested scroll was laggy as hell.

3. All rows regarding to NestedScrollingChildHelper were added - field and methods, look at the end of file.

4. "onScroll" and "onFling" methods.

I suppose, it's enough to get it working. If there's any troubles - inform me please, i will continue to dig.

**Comment by yarovoiag** [comment]
Hi @formatBCE, thx for using this library.
I see you did a good job )) Feel free to create pull request. We will integrate this changes in our library.
With best regards Cleveroad team.

**Comment by formatBCE** [comment]
Hey @yarovoiag! Will make it asap, thanks! :)
