### ISSUE TITLE
read from excel file

### ISSUE THREAD

**Issue by redlaam** [Cleveroad/AdaptiveTableLayout#25]
can u help me to read from xls file and display using your adaptive able by the way i can get cellule by cellule from my excel using Jecxel API (student project mobile application in android studio still beginner)

**Comment by yarovoiag** [comment]
Hi @redlaam , thx for using our library.
This library is not about reading from csv, xls, database. We created this library for working with big amount of data from any source.
With best regards Cleveroad team.
