### ISSUE TITLE
bug:scroll up or down will be flashing

### ISSUE THREAD

**Issue by jiang111** [Cleveroad/AdaptiveTableLayout#3]
Scroll up or down will be flashing When the content does not fill the entire screen

**Comment by yarovoiag** [comment]
Will be fixed in near future.

**Comment by sskucinski** [comment]
How to fix it:
Class: AdaptiveTableLayout

> 
    public void scrollBy(int x, int y) {
        // block scroll one axle
        int tempX = mState.isRowDragging() ? 0 : x;
        int tempY = mState.isColumnDragging() ? 0 : y;

        int diffX = tempX;
        int diffY = tempY;

        int shadowShiftX = mManager.getColumnCount() * mSettings.getCellMargin();
        int shadowShiftY = mManager.getRowCount() * mSettings.getCellMargin();

        long maxX = mManager.getFullWidth() + shadowShiftX;
        long maxY = mManager.getFullHeight() + shadowShiftY;

        if (mState.getScrollX() + tempX < 0) {
            // scroll over view to the left
            diffX = mState.getScrollX();
            mState.setScrollX(0);
        } else if (mSettings.getLayoutWidth() > maxX) {
            // few items and we have free space.
            diffX = 0;
            mState.setScrollX(0);
        } else if (mState.getScrollX() + mSettings.getLayoutWidth() + tempX > maxX) {
            // scroll over view to the right
            diffX = (int) (maxX - mState.getScrollX() - mSettings.getLayoutWidth());

            mState.setScrollX(mState.getScrollX() + diffX);
        } else {
            mState.setScrollX(mState.getScrollX() + tempX);
        }

        if (mState.getScrollY() + tempY < 0) {
            // scroll over view to the top
            diffY = mState.getScrollY();
            mState.setScrollY(0);
        } else if (mSettings.getLayoutHeight() > maxY) {
            // few items and we have free space.
            diffY = 0;
            mState.setScrollY(0);
        } else if (mState.getScrollY() + mSettings.getLayoutHeight() + tempY > maxY) {
            // scroll over view to the bottom
            diffY = (int) (maxY - mState.getScrollY() - mSettings.getLayoutHeight());
            mState.setScrollY(mState.getScrollY() + diffY);
        } else {
            mState.setScrollY(mState.getScrollY() + tempY);
        }

        if (diffX == 0 && diffY == 0) {
            return;
        }

        if (mAdapter != null) {
            // refresh views
            recycleViewHolders();
            mVisibleArea.set(mState.getScrollX(),
                    mState.getScrollY(),
                    mState.getScrollX() + mSettings.getLayoutWidth(),
                    mState.getScrollY() + mSettings.getLayoutHeight());
            addViewHolders(mVisibleArea);
            refreshViewHolders();
        }
    }

**Comment by yarovoiag** [comment]
Fixed in 1.1.1 version
