### ISSUE TITLE
java.lang.NegativeArraySizeException: -1

### ISSUE THREAD

**Issue by Kiarasht** [Cleveroad/AdaptiveTableLayout#6]
Anyone else getting this issue? I'm only running the sample with the demo CSV file.

> 04-24 11:40:54.124 487-487/com.cleveroad.tablelayout E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                        Process: com.cleveroad.tablelayout, PID: 487
>                                                                        java.lang.NegativeArraySizeException: -1
>                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableManager.init(AdaptiveTableManager.java:59)
>                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.initItems(AdaptiveTableLayout.java:224)
>                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.onLayout(AdaptiveTableLayout.java:143)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
>                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
>                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
>                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
>                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
>                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
>                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
>                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
>                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
>                                                                            at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
>                                                                            at android.view.View.layout(View.java:17938)
>                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
>                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
>                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
>                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
>                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
>                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
>                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:695)
>                                                                            at android.view.Choreographer.doFrame(Choreographer.java:631)
>                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
>                                                                            at android.os.Handler.handleCallback(Handler.java:739)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                            at android.os.Looper.loop(Looper.java:158)
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224)
>                                                                            at java.lang.reflect.Method.invoke(Native Method)
>                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by yarovoiag** [comment]
Fixed in version 1.1.1
