### ISSUE TITLE
Scroll flicker when content does not fill the screen

### ISSUE THREAD

**Issue by mruijzendaal** [Cleveroad/AdaptiveTableLayout#8]
I construct an adapter with small views that do not fill the entire width or height of the screen. When I try to scroll now, the content flickers between the top and bottom of the AdaptiveTableLayout. When I make the cells large enough everything is fine, though.

**Comment by sunnykinger** [comment]
exact same issue I have. I have one page that has single row... on the horizontal scrolling content flickers  between top and bottom.

**Comment by yarovoiag** [comment]
Was fixed in new version 1.1.1.
